# src/main_server.py
import os
import sys

# Force the project root directory into the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
import hmac
import hashlib
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("SEOSiri-Biometric-IoT-Guard")

# Shared cryptographic key used by the Flutter app's token generator
SHARED_DEVICE_KEY = b"seosiri_biometric_iot_secret_2026"

# Active verified sessions memory (representing verified human presence)
ACTIVE_SESSIONS = {}

@mcp.tool()
def verify_biometric_token(student_id: str, raw_token: str, action_subject: str = "iot/unlock") -> str:
    """
    Verifies that an incoming MQTT token generated by the biometric_iot_bridge 
    Flutter app is cryptographically valid and authenticates human presence.
    """
    clean_id = student_id.strip().lower()
    
    # Recalculate expected token: SHA-256 of (secret + subject)
    payload = f"{clean_id}:{action_subject}".encode('utf-8')
    expected_token = hmac.new(SHARED_DEVICE_KEY, payload, hashlib.sha256).hexdigest()
    
    # Cryptographically secure comparison to prevent timing attacks
    if hmac.compare_digest(expected_token, raw_token):
        import time
        expiry = time.time() + 300
        ACTIVE_SESSIONS[clean_id] = {"action": action_subject, "expires_at": expiry}
        
        return json.dumps({
            "status": "AUTHENTICATED",
            "student_id": clean_id,
            "action_subject": action_subject,
            "session_expiry_epoch": int(expiry),
            "message": "Cryptographic biometric token verified. Human presence confirmed."
        })
        
    return json.dumps({
        "status": "REJECTED",
        "reason": "INVALID_SIGNATURE_OR_EXPIRED_TOKEN",
        "student_id": clean_id
    })

@mcp.tool()
def authorize_agent_actuation(student_id: str, proposed_action: str) -> str:
    """
    Sovereign Safety Gatekeeper: Ensures that an AI agent cannot trigger a physical 
    IoT device (e.g. unlocking a door) unless the user's biometric state is active.
    """
    clean_id = student_id.strip().lower()
    session = ACTIVE_SESSIONS.get(clean_id)
    
    if not session:
        return json.dumps({
            "status": "BLOCKED",
            "reason": "NO_ACTIVE_BIOMETRIC_SESSION",
            "remediation": "Please authenticate via your SEOSiri Mobile App FaceID/Fingerprint."
        })
        
    import time
    if time.time() > session["expires_at"]:
        ACTIVE_SESSIONS.pop(clean_id, None)
        return json.dumps({
            "status": "BLOCKED",
            "reason": "BIOMETRIC_SESSION_EXPIRED",
            "remediation": "Biometric session timed out. Re-authentication required."
        })
        
    if session["action"] != proposed_action:
        return json.dumps({
            "status": "BLOCKED",
            "reason": "UNAUTHORIZED_ACTION_SUBJECT",
            "remediation": f"Active session is only authorized for: {session['action']}"
        })
        
    return json.dumps({
        "status": "APPROVED",
        "student_id": clean_id,
        "authorized_action": proposed_action,
        "gcode_actuation_command": "G1 X180.0 F500.0"
    })

if __name__ == "__main__":
    import time
    time.sleep(0.5)
    mcp.run(transport='stdio')
